=== AitorCarlos/RAIZ/FASES/FASE 1/LM/ultimaJornada.dtd
<!ELEMENT jornada (datosLiga, datosJornada, partidos)>
        <!ELEMENT datosLiga (nombre)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT datosJornada (codigo, nombre, fecha)>
        <!ELEMENT codigo (#PCDATA)>
        <!ELEMENT fecha (#PCDATA)>
        <!ELEMENT partidos (partido)+>
        <!ELEMENT partido (codigo, fecha, nombreE1, nombreE2, resultadoE1, resultadoE2)*>
        <!ATTLIST partido
                jugado CDATA #REQUIRED>
        <!ELEMENT nombreE1 (#PCDATA)>
        <!ELEMENT nombreE2 (#PCDATA)>
        <!ELEMENT resultadoE1 (#PCDATA)>
        <!ELEMENT resultadoE2 (#PCDATA)>

=== AitorCarlos/RAIZ/FASES/FASE 1/LM/ultimaJornada.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE jornada SYSTEM "ultimaJornada.dtd">
<jornada>
    <datosLiga>
        <nombre></nombre>
    </datosLiga>
    <datosJornada>
        <codigo></codigo>
        <nombre></nombre>
        <fecha></fecha>
    </datosJornada>
    <partidos>
        <partido jugado="">
            <codigo></codigo>
            <fecha></fecha>
            <nombreE1></nombreE1>
            <nombreE2></nombreE2>
            <resultadoE1></resultadoE1>
            <resultadoE2></resultadoE2>
        </partido>
    </partidos>
</jornada>
